spring.application.name=Presentation

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.show-sql=true

spring.security.user.name=admin
spring.security.user.password=admin

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto = update

token.signing.key=Nx4a9U0L1GNvkxVU45qDDxYy3mCU9CC4RYC13jAU0v9IKAAKk4wd+cEV+wukOklm